#!/usr/bin/env zsh

cd ${0:A:h}

case "$1" in
compile)
	if [ ! -f package.json ]; then
		npm init -y
		npm install google-protobuf
		mkdir -p proto-out
	fi
	protoc --js_out=import_style=commonjs,binary:./proto-out ./boilerplate.proto

	mkdir -p proto_out_python
	protoc --python_out=proto_out_python ./boilerplate.proto
	;;
clean)
	rm -rf proto-out proto_out_python package.json package-lock.json node_modules
	;;
esac